IPSEC=${IPSEC:-"0"}
MACSEC=${MACSEC:-"0"}
CONNECTION=${CONNECTION-"0"}
LOG_LEVEL=${LOG_LEVEL-"1"}

make clean
make sender LOG_LEVEL=${LOG_LEVEL} CONNECTION=${CONNECTION} IPSEC=${IPSEC} MACSEC=${MACSEC} ADDR_BYTE_4=2 RECEIVER_ADDR=192.168.1.3
make clean
make receiver LOG_LEVEL=${LOG_LEVEL} CONNECTION=${CONNECTION} IPSEC=${IPSEC} MACSEC=${MACSEC} ADDR_BYTE_4=3 RECEIVER_ADDR=192.168.1.3
make clean
make app LOG_LEVEL=${LOG_LEVEL} CONNECTION=${CONNECTION} IPSEC=${IPSEC} MACSEC=${MACSEC} ADDR_BYTE_4=200 RECEIVER_ADDR=127.0.0.1
make clean
